version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=createnshare-test-1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Chiraag@001
  web:
    build: .
    env_file: createnshare/.env
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:3003"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db